import {
  AlertTriangle,
  BatteryLow,
  BellOff,
  Banknote,
  Building2,
  Calculator,
  CalendarX,
  Car,
  ClipboardCheck,
  ClipboardList,
  CloudLightning,
  DoorOpen,
  Droplets,
  Eye,
  Gauge,
  GraduationCap,
  HandPlatter,
  Heart,
  Hourglass,
  LayoutGrid,
  MessageCircleWarning,
  MessageSquare,
  PackageCheck,
  Receipt,
  ScanLine,
  Shield,
  ShieldAlert,
  ShoppingCart,
  Sparkles,
  StickyNote,
  Tag,
  Thermometer,
  Trash2,
  TrendingDown,
  TrendingUp,
  Truck,
  Undo2,
  UserMinus,
  UserRound,
  Users,
  Video,
  Wheat,
} from "lucide-react";

const MAP: Record<string, React.ComponentType<{ className?: string }>> = {
  alert_triangle: AlertTriangle,
  banknote: Banknote,
  battery_low: BatteryLow,
  bell_off: BellOff,
  building2: Building2,
  calculator: Calculator,
  calendar_x: CalendarX,
  car: Car,
  clipboard_check: ClipboardCheck,
  clipboard_list: ClipboardList,
  cloud_lightning: CloudLightning,
  door_open: DoorOpen,
  droplets: Droplets,
  eye: Eye,
  gauge: Gauge,
  graduation_cap: GraduationCap,
  hand_platter: HandPlatter,
  heart: Heart,
  hourglass: Hourglass,
  layout_grid: LayoutGrid,
  message_circle_warning: MessageCircleWarning,
  message_square: MessageSquare,
  package_check: PackageCheck,
  receipt: Receipt,
  scan_line: ScanLine,
  shield: Shield,
  shield_alert: ShieldAlert,
  shopping_cart: ShoppingCart,
  sparkles: Sparkles,
  sticky_note: StickyNote,
  tag: Tag,
  thermometer: Thermometer,
  trash2: Trash2,
  trending_down: TrendingDown,
  trending_up: TrendingUp,
  truck: Truck,
  undo2: Undo2,
  user_minus: UserMinus,
  user_round: UserRound,
  users: Users,
  video: Video,
  wheat: Wheat,
};

export function ScenarioIcon({
  name,
  fallback: Fallback = AlertTriangle,
  className,
}: {
  name?: string;
  fallback?: React.ComponentType<{ className?: string }>;
  className?: string;
}) {
  const Icon = name ? MAP[name] ?? Fallback : Fallback;
  return <Icon className={className} />;
}
