import type { Alert, Issue, DisruptionEvent } from "@sim/shared";

export const ISSUE_BANK: Issue[] = [
  {
    id: "iss_short_stock",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Short-dated stock build-up",
    description: "Chilled aisle has 180 units within 24h expiry.",
    severity: "medium",
    tags: ["commercial", "safety_loss"],
    icon: "package_check",
  },
  {
    id: "iss_till_queue",
    urgency: 4,
    type: "A",
    scored: true,
    title: "Till queue exceeding 8 minutes",
    description: "Front-end service levels breaching threshold.",
    severity: "high",
    tags: ["customer", "commercial"],
    icon: "hourglass",
  },
  {
    id: "iss_sickness",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Two team members absent",
    description: "Duty manager short-handed in backroom.",
    severity: "medium",
    tags: ["people_team"],
    icon: "user_minus",
  },
  {
    id: "iss_theft_pattern",
    urgency: 4,
    type: "A+B",
    scored: false,
    title: "Repeat shoplifting pattern flagged",
    description: "Security footage shows three incidents this week in spirits aisle.",
    severity: "high",
    tags: ["safety_loss"],
    icon: "shield_alert",
  },
  {
    id: "iss_delivery_late",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Delivery running 90 minutes late",
    description: "Backroom team blocked, shop floor gaps forming.",
    severity: "medium",
    tags: ["commercial"],
    icon: "truck",
  },
  {
    id: "iss_complaint_escalation",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Customer complaint escalated",
    description: "Refund refused at self-scan, customer demanding manager.",
    severity: "medium",
    tags: ["customer"],
    icon: "message_circle_warning",
  },
  {
    id: "iss_team_conflict",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Interpersonal conflict on nights team",
    description: "Supervisor flagged a dispute affecting morale and output.",
    severity: "medium",
    tags: ["people_team"],
    icon: "users",
  },
  {
    id: "iss_planogram",
    urgency: 2,
    type: "A",
    scored: true,
    title: "Planogram compliance at 62%",
    description: "Head Office flagged compliance shortfall in beers & wines.",
    severity: "low",
    tags: ["commercial"],
    icon: "layout_grid",
  },
  {
    id: "iss_waste",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Waste tracking 14% above target",
    description: "Bakery and produce departments over index this week.",
    severity: "medium",
    tags: ["commercial", "safety_loss"],
    icon: "trash2",
  },
  {
    id: "iss_wet_floor",
    urgency: 5,
    type: "A+B",
    scored: false,
    title: "Unreported spillage in aisle 7",
    description: "Wet floor sign missing. A customer flagged it, colleague had walked past twice.",
    severity: "high",
    tags: ["safety_loss", "customer"],
    icon: "droplets",
  },
  {
    id: "iss_safeguarding",
    urgency: 5,
    type: "A+B",
    scored: false,
    title: "Possible safeguarding concern",
    description: "Colleague raised worry about an unaccompanied child who has been in store for 40 minutes.",
    severity: "high",
    tags: ["safety_loss", "customer"],
    icon: "eye",
  },
  {
    id: "iss_new_starter_overwhelmed",
    urgency: 3,
    type: "A",
    scored: true,
    title: "New starter visibly struggling",
    description: "Two weeks in, hasn't eaten lunch all week. Peers sensing it but saying nothing.",
    severity: "medium",
    tags: ["people_team"],
    icon: "user_round",
  },
  {
    id: "iss_cash_variance",
    urgency: 4,
    type: "A+B",
    scored: false,
    title: "Till float variance on two desks",
    description: "Same colleague signed both off. Pattern rather than a one-off.",
    severity: "medium",
    tags: ["safety_loss"],
    icon: "banknote",
  },
  {
    id: "iss_bread_outage",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Fresh bread range 40% out",
    description: "In-store bake behind schedule, peak trade in an hour.",
    severity: "medium",
    tags: ["commercial", "customer"],
    icon: "wheat",
  },
  {
    id: "iss_trolley_return",
    urgency: 2,
    type: "A",
    scored: true,
    title: "Car park trolleys stacked up",
    description: "Colleague rota for retrieval slipped. Complaints starting at customer service.",
    severity: "low",
    tags: ["customer"],
    icon: "shopping_cart",
  },
  {
    id: "iss_fridge_warm",
    urgency: 5,
    type: "A+B",
    scored: false,
    title: "Fridge running 2C above spec",
    description: "Engineer called last week, same unit flagged again. Stock still on sale.",
    severity: "high",
    tags: ["safety_loss", "commercial"],
    icon: "thermometer",
  },
  {
    id: "iss_self_scan_errors",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Self-scan error rate spiking",
    description: "One bank throwing item-not-recognised errors. Supervisor overrides tracking at 40 per hour.",
    severity: "medium",
    tags: ["customer", "commercial"],
    icon: "scan_line",
  },
  {
    id: "iss_lone_working",
    urgency: 4,
    type: "A+B",
    scored: false,
    title: "Lone working on customer service desk",
    description: "Second colleague pulled away for an escalation, desk covered solo for the last 30 minutes.",
    severity: "medium",
    tags: ["people_team", "safety_loss"],
    icon: "user_round",
  },
  {
    id: "iss_aggressive_customer",
    urgency: 4,
    type: "A+B",
    scored: false,
    title: "Customer verbally aggressive to colleague",
    description: "Incident logged but colleague back on shop floor. Wellbeing unclear.",
    severity: "high",
    tags: ["people_team", "safety_loss"],
    icon: "shield_alert",
  },
  {
    id: "iss_promo_pricing",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Promotion pricing error",
    description: "Shelf edge shows 2-for-5, till rings up at full price. Complaints building.",
    severity: "medium",
    tags: ["customer", "commercial"],
    icon: "tag",
  },
  {
    id: "iss_online_picking",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Online picking behind target",
    description: "Van leaves in 45 minutes. Pickers short two colleagues, trolleys half done.",
    severity: "medium",
    tags: ["commercial", "customer"],
    icon: "clipboard_list",
  },
  {
    id: "iss_staff_whatsapp",
    urgency: 2,
    type: "A",
    scored: true,
    title: "Store WhatsApp group getting heated",
    description: "Screenshots circulating about a manager's tone. You've not been added to the group.",
    severity: "medium",
    tags: ["people_team"],
    icon: "message_square",
  },
  {
    id: "iss_health_visit",
    urgency: 5,
    type: "A+B",
    scored: false,
    title: "EHO visit this afternoon",
    description: "Environmental Health confirmed arrival between 2 and 4pm. Bakery prep area last audit flagged two actions.",
    severity: "high",
    tags: ["safety_loss", "commercial"],
    icon: "clipboard_check",
  },
  {
    id: "iss_schedule_short",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Weekend rota undersized",
    description: "Saturday shows 11 colleagues against a forecast of 14. Two pending holiday approvals sitting with you.",
    severity: "medium",
    tags: ["people_team", "commercial"],
    icon: "calendar_x",
  },
  {
    id: "iss_markdown_pattern",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Markdowns concentrated on one aisle",
    description: "Produce hitting 60% markdown rate this week. Buyer emailed asking for a store view by end of day.",
    severity: "medium",
    tags: ["commercial"],
    icon: "trending_down",
  },
  {
    id: "iss_colleague_photo",
    urgency: 4,
    type: "A+B",
    scored: false,
    title: "Colleague filmed a customer on their phone",
    description: "Colleague says it was for evidence of aggressive behaviour. Customer saw and is threatening to report.",
    severity: "high",
    tags: ["people_team", "safety_loss", "customer"],
    icon: "video",
  },
  {
    id: "iss_returns_trend",
    urgency: 5,
    type: "A+B",
    scored: false,
    title: "Returns spike on a single SKU",
    description: "14 returns of the same baby formula in 48 hours, same batch code. No recall notice yet.",
    severity: "high",
    tags: ["safety_loss", "customer"],
    icon: "undo2",
  },
  {
    id: "iss_supplier_demo",
    urgency: 2,
    type: "A",
    scored: true,
    title: "Unplanned supplier in-store demo",
    description: "Supplier rep has set up a sampling stand without booking. Engaging customers, blocking an aisle.",
    severity: "low",
    tags: ["commercial", "customer"],
    icon: "hand_platter",
  },
  {
    id: "iss_till_closed_sign",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Handwritten 'closed' signs on tills",
    description: "Three tills hand-labelled closed by a colleague who said they were too tired to run them. No authorisation.",
    severity: "medium",
    tags: ["customer", "people_team"],
    icon: "sticky_note",
  },
  {
    id: "iss_stocktake_variance",
    urgency: 4,
    type: "A+B",
    scored: false,
    title: "Overnight stocktake variance",
    description: "High-value category off by 1.8%. Unusual for the store. Loss prevention pinging for a view.",
    severity: "medium",
    tags: ["safety_loss", "commercial"],
    icon: "calculator",
  },
  // --- Added from the SME validation pack (equipment family + war stories) as
  // playable placeholders. Weights/tags/severity provisional until SME sign-off.
  {
    id: "iss_scales_fault",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Counter scales / weigh-station fault",
    description: "Deli, butchery or bakery counter cannot weigh and price.",
    severity: "medium",
    tags: ["commercial", "customer"],
    icon: "calculator",
  },
  {
    id: "iss_baler_fault",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Baler / compactor failure",
    description: "Cardboard and waste back up in the warehouse, blocking walkways.",
    severity: "medium",
    tags: ["safety_loss", "commercial"],
    icon: "trash2",
  },
  {
    id: "iss_doors_fault",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Automatic doors / shutters fault",
    description: "Entrance doors stuck or shutter jammed at open or close.",
    severity: "medium",
    tags: ["customer", "safety_loss"],
    icon: "shield_alert",
  },
  {
    id: "iss_aircon_fault",
    urgency: 2,
    type: "A",
    scored: true,
    title: "Air-con / HVAC comfort failure",
    description: "Sales floor or backroom uncomfortably hot for colleagues and customers.",
    severity: "low",
    tags: ["people_team", "customer"],
    icon: "thermometer",
  },
  {
    id: "iss_work_around_process",
    urgency: 4,
    type: "A+B",
    scored: false,
    title: "Team working around process",
    description: "A team delivers results but works outside the guidelines set by the organisation.",
    severity: "medium",
    tags: ["safety_loss", "people_team"],
    icon: "clipboard_check",
  },
  {
    id: "iss_customer_accident",
    urgency: 5,
    type: "A+B",
    scored: false,
    title: "Customer accident in store or car park",
    description: "A customer is injured; reporting and duty-of-care obligations apply.",
    severity: "high",
    tags: ["safety_loss", "customer"],
    icon: "shield_alert",
  },
  {
    id: "iss_change_project",
    urgency: 3,
    type: "A",
    scored: true,
    title: "Change project has not landed",
    description: "A major project from before you arrived is only half embedded and must be revisited before peak.",
    severity: "medium",
    tags: ["commercial", "people_team"],
    icon: "clipboard_list",
  },
  {
    id: "iss_conduct_case",
    urgency: 4,
    type: "A+B",
    scored: false,
    title: "Conduct or grievance case",
    description: "An employee relations case lands in your first week - a suspension, dismissal or grievance.",
    severity: "high",
    tags: ["people_team"],
    icon: "users",
  },
];

export const ALERT_BANK: Omit<Alert, "id" | "timestamp">[] = [
  {
    kind: "head_office",
    title: "Head Office: weekly compliance review",
    message: "Regional visit next Tuesday, availability audit expected.",
    icon: "building2",
  },
  {
    kind: "operational",
    title: "Chiller alarm temporarily silenced",
    message: "Engineering callout logged, response in 45 minutes.",
    icon: "bell_off",
  },
  {
    kind: "head_office",
    title: "Head Office: price file update live",
    message: "118 SKUs changed overnight, verify edge labels.",
    icon: "tag",
  },
  {
    kind: "operational",
    title: "Self-scan unit 4 offline",
    message: "Awaiting engineer, divert customers to manned tills.",
    icon: "scan_line",
  },
  {
    kind: "head_office",
    title: "Head Office: new range launch Thursday",
    message: "Free-from range expanding 40 SKUs. POS and ranging brief in the morning pack.",
    icon: "sparkles",
  },
  {
    kind: "operational",
    title: "Fire door alarmed overnight",
    message: "Security log shows it was wedged open between 2 and 4am. No one flagged it.",
    icon: "door_open",
  },
  {
    kind: "head_office",
    title: "Mandatory refresher training due",
    message: "Age-restricted sales module closes Friday, 14 colleagues still outstanding.",
    icon: "graduation_cap",
  },
  {
    kind: "operational",
    title: "Trolley wash rota skipped",
    message: "Last two nights missed. Colleague said they weren't sure whose task it was this week.",
    icon: "shopping_cart",
  },
  {
    kind: "operational",
    title: "Handheld scanner battery bank empty",
    message: "Backroom team losing scan time waiting for replacements.",
    icon: "battery_low",
  },
  {
    kind: "head_office",
    title: "Head Office: social media callout",
    message: "Your store tagged in a positive local post about a colleague. 3,200 likes so far.",
    icon: "heart",
  },
  {
    kind: "operational",
    title: "Sprinkler inspection outstanding",
    message: "Annual check was due last month. Contractor has rebooked twice. Next slot is Friday.",
    icon: "shield",
  },
  {
    kind: "head_office",
    title: "Peak trade window shift",
    message: "Regional data shows peak moving 40 minutes later this week. Staffing plan may need a look.",
    icon: "trending_up",
  },
  {
    kind: "operational",
    title: "Goods-in dock blocked",
    message: "Third party delivery overshot its window, still unloading. Our slot now at risk.",
    icon: "truck",
  },
  {
    kind: "head_office",
    title: "Head Office: colleague survey pulse",
    message: "Store's engagement pulse sits below cluster average. Cluster lead has asked for a 10-line response.",
    icon: "gauge",
  },
  {
    kind: "operational",
    title: "Till receipt roll stock low",
    message: "Two banks ran out during yesterday's peak. Order not placed.",
    icon: "receipt",
  },
  {
    kind: "head_office",
    title: "Weather warning: amber",
    message: "Met Office amber wind warning from 4pm. Traffic and customer flow impact likely.",
    icon: "cloud_lightning",
  },
  {
    kind: "operational",
    title: "Colleague parking permit dispute",
    message: "Three colleagues clamped this week. Contractor says they had correct permits.",
    icon: "car",
  },
];

export const DISRUPTION_BANK: Omit<DisruptionEvent, "id" | "triggeredAt">[] = [
  {
    title: "Fire alarm activation",
    message: "Full evacuation triggered by a faulty smoke detector in backroom.",
    impact: "Shop floor unattended for 12 minutes, safety and trust under pressure.",
    scene: "fire_alarm",
  },
  {
    title: "Competitor flash promotion",
    message: "Rival store launched a 25% off promotion within the hour.",
    impact: "Sales pressure intensifies, requires commercial response.",
    scene: "competitor_promo",
  },
  {
    title: "Viral customer complaint",
    message: "Social media post about till queues gaining traction.",
    impact: "Customer experience KPI under scrutiny from Head Office.",
    scene: "viral_complaint",
  },
  {
    title: "Key colleague walks out",
    message: "A senior team member left mid-shift citing pressure.",
    impact: "Trust and capability hits; engagement at risk.",
    scene: "colleague_walkout",
  },
  {
    title: "Power outage in backroom",
    message: "Chilled goods at risk, 30 minute window.",
    impact: "Shrinkage and operations under threat.",
    scene: "power_outage",
  },
  {
    title: "Medical incident in store",
    message: "A customer has collapsed near customer service. Colleagues are first-aid trained but visibly rattled.",
    impact: "Immediate safety response required, team focus split, customer experience watching.",
    scene: "medical_incident",
  },
  {
    title: "Product recall goes live",
    message: "Head Office pushed an immediate recall on a bakery line. Product still on sale in 40 stores including yours.",
    impact: "Safety and trust pressure, requires coordinated removal across the floor in minutes.",
    scene: "product_recall",
  },
  {
    title: "Till system partial outage",
    message: "Half the till banks are frozen on a card-network issue. Cash still working, queues doubling every minute.",
    impact: "Customer experience and operations under simultaneous pressure.",
    scene: "till_outage",
  },
  {
    title: "Minor flood from overhead pipe",
    message: "Water coming through the ceiling near wines and spirits. Stock exposed, electricals nearby.",
    impact: "Safety, shrinkage, and customer perception all live at once.",
    scene: "flood",
  },
  {
    title: "Unannounced director visit",
    message: "A group retail director has arrived unannounced for a walk-round. They're at the lift now.",
    impact: "Leadership consistency under the microscope, every decision visible.",
    scene: "director_visit",
  },
  {
    title: "Local news crew on the forecourt",
    message: "A reporter is asking customers about a national story that mentions your store by name.",
    impact: "Public-facing trust pressure, colleague discipline matters, no time to brief.",
    scene: "news_crew",
  },
  {
    title: "Colleague accused of theft by a customer",
    message: "Customer publicly accused a colleague of pocketing a returned item. Crowd forming.",
    impact: "Trust, safety and customer experience all colliding with a live audience.",
    scene: "theft_accusation",
  },
  {
    title: "Delivery partner crashed in car park",
    message: "A third-party driver reversed into two customer cars. No injuries, insurance chase starting.",
    impact: "Customer experience and operations shift in an instant.",
    scene: "delivery_crash",
  },
  {
    title: "Server room overheating",
    message: "Air-con unit in the comms room has failed. Systems warning is live, stock ordering at risk.",
    impact: "Operations exposure; backroom decisions become time-boxed.",
    scene: "server_overheating",
  },
];
